apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - image: eynet/maint:latest
        name: angular
        ports:
        - containerPort: 80